[program:discord-bot]
command=/usr/bin/python3.8 -u /home/brikez/scripts/bot.py
directory=/home/brikez/scripts
autostart=true
autorestart=true
stopsignal=TERM
stdout_logfile=/home/brikez/log/discord-bot.out.log
stderr_logfile=/home/brikez/log/discord-bot.err.log
environment=PYTHONUNBUFFERED="1"
# startsecs is set by Uberspace monitoring team, to prevent a broken service from looping
startsecs=30